name: shobek_lobek
description: shobek lobek food delivery application, order food online

version: 1.1.5+14

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^0.3.10
  flutter_inner_drawer: ^0.5.5
  flutter_colorpicker: ^0.3.2
  dropdown_banner: ^1.4.0
  http: ^0.12.0+4
  pull_to_refresh: ^1.5.8
  shared_preferences: ^0.5.4+8
  flutter_flip_view: ^1.0.3
  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/main-logo.png
    - assets/loading.gif
